### PR TITLE
Update call_function_with_args_resolved()

### PR DESCRIPTION
**Pull request by sheisc**
Fix a bug in call_function_with_args_resolved().

### CODE REVIEW

**Review by rocky — APPROVED** [review]
Thanks!

**Comment by rocky** [comment]
Can you come up with a test case to show an example of how this changes fixes things?

**Comment by sheisc** [comment]
A test case for it.  Thanks a lot for your amazing x-python. 

```
x = 2023

def f():
    y = 2024
    assert locals() != globals()

f()
```

**Comment by rocky** [comment]
> A test case for it. Thanks a lot for your amazing x-python.
> 
> ```
> x = 2023
> 
> def f():
>     y = 2024
>     assert locals() != globals()
> 
> f()
> ```

Good!  Now let's add this as a test case that gets run. 

To do this...

<strike>Unzip the attached file :  [x-python-globals-an-locals-test.diff.zip](https://github.com/rocky/x-python/files/13466264/x-python-globals-an-locals-test.diff.zip)

and run `patch -p1 < x-python-globals-and-locals-test.diff`

or</strike> (More tests added below.)

Save this file:

```python
"""This program is self-checking!"""

x = 2023
def f():
    assert 2023 == globals()["x"]    
    assert "y" not in locals()
    y = 2024
    assert 2024 == locals()["y"]
    assert locals() != globals()

f()
```

 to `test/examples/functions/test_locals_and_globals.py` in your `x-python` repository.

`git add test/examples/functions/test_locals_and_globals.py`

Then in `test` run  `./add-single-test.sh examples/functions/test_locals_and_globals.py` and "git add" the bytecode file that gets created.  Run "xpython" on the bytecode file to see that the "assert"s succeed. And finally run `make check` to see that everything works.

**Comment by rocky** [comment]
As for the state of x-python itself, first this builds on the work of two other people (who abandoned it). 

The code still needs a lot of work many places, and I haven't time to devote improving this. 

However I  have focused on is making this more scalable across Python version changes, and reworked how testing works. Also there is a debugger for this that I personally use a bit: trepan-xpy.

**Comment by sheisc** [comment]
Hi Rocky. Thank you for teaching me so patiently about how to add a test case into x-python. I only tested it on CPython3.9.0.

**Review by rocky — APPROVED** [review]
LGTM. And Thanks!

**Pull request merged**
